package EjRepaso1;

public enum ProvinciaEleccion {
    BUENOSAIRES, CIUDADAUTÓNOMADEBUENOSAIRES, CATAMARCA,CHACO,CHUBUT,CÓRDOBA ,CORRIENTES,ENTRERIOS,FORMOSA ,JUJUY, LAPAMPA,LARIOJA,MENDOZA,MISIONES ,NEUQUÉN, RIONEGRO, SALTA,SANJUAN, SANLUIS, SANTACRUZ, SANTAFE, SANTIAGODELESTERO, TIERRADELFUEGO, TUCUMÁN
}
